"""
Django's settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

import cloudinary
import cloudinary.api
import cloudinary.uploader
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

load_dotenv(".env.development.local")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3+(4zz#u&=rl8c-t4s3)l8t3gfem)r2b8g$r#4g#ms+2s2^zo8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app', '.now.sh']

# Application definition

INSTALLED_APPS = [
	# core
	'home.apps.HomeConfig',
	'user.apps.AccountsConfig',
	'company.apps.CompanyConfig',
	'job.apps.JobConfig',
	'settings.apps.SettingsConfig',
	'cv.apps.CvManagementConfig',
	# CKEditor
	'django_ckeditor_5',
	# SSLServer
	'sslserver',
	# Django
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',
	# Django-allauth
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',
	'allauth.socialaccount.providers.facebook',
	# Cloudinary
	'cloudinary',
	'cloudinary_storage',
]

SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'SCOPE': [
			'profile',
			'email',
		],
		'AUTH_PARAMS': {
			'access_type': 'online',
		},
	},
	'facebook': {
		'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
		'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
		'SCOPE': ['email', 'public_profile'],
		'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
		'INIT_PARAMS': {'cookie': True},
		'FIELDS': [
			'id',
			'email',
			'name',
			'first_name',
			'last_name',
			'verified',
			'locale',
			'timezone',
			'link',
			'gender',
			'updated_time'
		],
		'EXCHANGE_TOKEN': True,
		'LOCALE_FUNC': 'path.to.callable',
		'VERIFIED_EMAIL': False,
		'VERSION': 'v13.0',
		'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
	},
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'home.context_processors.context_processors',
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'core.wsgi.app'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
	# 'default': {
	# 	'ENGINE': 'django.db.backends.postgresql_psycopg2',
	# 	'URL': os.getenv('POSTGRES_URL'),
	# 	'NAME': os.getenv('POSTGRES_DATABASE'),
	# 	'USER': os.getenv('POSTGRES_USER'),
	# 	'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
	# 	'HOST': os.getenv('POSTGRES_HOST'),
	# 	'PORT': os.getenv('POSTGRES_PORT'),
	# },
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'career_consulting_db',
		'USER': 'root',
		'PASSWORD': '29012003',
		'HOST': 'localhost'
	},
	# 'default': {
	# 	'ENGINE': 'django.db.backends.sqlite3',
	# 	'NAME': BASE_DIR / 'db.sqlite3',
	# },
}

AUTH_USER_MODEL = 'home.Account'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

SITE_ID = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

cloudinary.config(
	cloud_name="dtthwldgs",
	api_key="295661242477252",
	api_secret="xKPY2fG-4h1mtZl2_PRvxsSfgtA",
)

LOGIN_URL = '/account/login/'
LOGOUT_URL = '/'

STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
DEFAULT_AVATAR = os.path.join(STATIC_URL, 'images/default-avatar.jpg')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
	'django.contrib.auth.backends.ModelBackend',
	'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[core] - '
ACCOUNT_MAX_EMAIL_ADDRESSES = 1

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM = 'pythonlessons0@gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hieptt.2003@gmail.com'
EMAIL_HOST_PASSWORD = "afva qqxt wzrs ikyn"
EMAIL_USE_TLS = True
PASSWORD_RESET_TIMEOUT = 14400

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'home.adapter.CustomSocialAccountAdapter'

RECAPTCHA_PUBLIC_KEY = '6Lfc7CMpAAAAACNWeUL_2_6KoWJX574WMypSf0BH'
RECAPTCHA_PRIVATE_KEY = '6Lfc7CMpAAAAALBnFhTB9560YylOXf_HYwF_-EI7'

customColorPalette = [
	{
		'color': 'hsl(4, 90%, 58%)',
		'label': 'Red'
	},
	{
		'color': 'hsl(340, 82%, 52%)',
		'label': 'Pink'
	},
	{
		'color': 'hsl(291, 64%, 42%)',
		'label': 'Purple'
	},
	{
		'color': 'hsl(262, 52%, 47%)',
		'label': 'Deep Purple'
	},
	{
		'color': 'hsl(231, 48%, 48%)',
		'label': 'Indigo'
	},
	{
		'color': 'hsl(207, 90%, 54%)',
		'label': 'Blue'
	},
]

# CKEDITOR_5_CUSTOM_CSS = 'path_to.css'
CKEDITOR_5_FILE_STORAGE = "home.storage.CustomStorage"
CKEDITOR_5_CONFIGS = {
	'default': {
		'toolbar': ['heading', '|', 'bold', 'italic', 'link',
		            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

	},
	'extends': {
		'blockToolbar': [
			'paragraph', 'heading1', 'heading2', 'heading3',
			'|',
			'bulletedList', 'numberedList',
			'|',
			'blockQuote',
		],
		'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
		            'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
		            'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
		            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
		            'insertTable', ],
		'image': {
			'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
			            'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
			'styles': [
				'full',
				'side',
				'alignLeft',
				'alignRight',
				'alignCenter',
			]

		},
		'table': {
			'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
			                   'tableProperties', 'tableCellProperties'],
			'tableProperties': {
				'borderColors': customColorPalette,
				'backgroundColors': customColorPalette
			},
			'tableCellProperties': {
				'borderColors': customColorPalette,
				'backgroundColors': customColorPalette
			}
		},
		'heading': {
			'options': [
				{'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
				{'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
				{'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
				{'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
			]
		}
	},
	'list': {
		'properties': {
			'styles': 'true',
			'startIndex': 'true',
			'reversed': 'true',
		}
	}
}
