# Generated by Django 5.0.3 on 2024-04-02 17:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('address', models.CharField(max_length=100, null=True)),
                ('number_of_employees', models.IntegerField(default=0, null=True)),
                ('social_link', models.CharField(max_length=254, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
